version: '3.5'

services:
  postgres:
    container_name: solar_boat_postgres
    image: postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: solar-boat-db
    volumes:
       - boat_postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - solar_infra
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - solar_infra
    restart: unless-stopped

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - solar_infra
    ports:
      - "6379:6379"
    restart: unless-stopped

networks:
  solar_infra:
    driver: bridge

volumes:
    boat_postgres:
    pgadmin: