name: Master

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-publish-latest:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v2 # Checking out the repo

          - name: Build and Publish latest Docker image
            uses: VaultVulp/gp-docker-action@1.1.12
            with:
                github-token: ${{ secrets.REGISTRY_TOKEN }}
                image-name: solar-infra-runner
                dockerfile: devenv/runner/Dockerfile